// Code generated by "stringer -type=URLPart -trimprefix URL"; DO NOT EDIT.

package format

func _() {
	_ = "STUB: not implemented"
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	return
}

const _URLPart_name = "QueryUserPasswordHostPortPath"

var _URLPart_index = [...]uint8{0, 5, 9, 17, 21, 25, 29}

func (i URLPart) String() string { _ = "STUB: not implemented"; return "" }
